#!/usr/bin/env python3
"""Compile storyboard/shots.json into per-shot video generation prompts.

The video counterpart of build_prompts.py. That script compiles the superseded
13-panel comic track (3:4 stills); this one compiles the authoritative 24-shot
video storyboard (16:9). They stay separate on purpose — the two tracks carry
different aspect ratios and different negative prompts, and merging them would
make an edit to one silently rewrite the other.

Prompts extend the comic's 4-element structure with the two things a video model
needs and a still does not: clip duration, and how the motion sits on the beat.

    character / expression / action+camera / motion+duration / style

Usage:
    python scripts/build_shots.py                    # write out/shot_prompts.{json,md}
    python scripts/build_shots.py --show S12         # print one shot
    python scripts/build_shots.py --model "ComfyUI MiniMax H3"  # print local batch
"""
import argparse
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BPM = 106


def load(name):
    return json.loads((ROOT / name).read_text(encoding="utf-8"))


def build_prompt(shot, defaults, character):
    """Assemble the 5-element video prompt."""
    character_desc = ", ".join(character["locked_keywords"])
    parts = [
        f'{character["name"]}, a K-pop virtual idol: {character_desc}',
        f'expression: {shot["expression"]}',
        f'{shot["action"]}; camera: {shot["camera"]}',
        f'duration {shot["dur"]:.2f}s, motion synced to {BPM} BPM; '
        f'{shot["sync"].rstrip(". ")}',
        defaults["style_suffix"],
    ]
    return ". ".join(parts)


def shot_hash(prompt, negative, ratio):
    """Same rule as build_prompts.py: only re-render what actually changed."""
    payload = json.dumps([prompt, negative, ratio], ensure_ascii=False)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:12]


def compile_shots(project, book, lyrics_by_id):
    defaults = book["defaults"]
    character = project["character"]

    compiled = []
    for shot in book["shots"]:
        prompt = build_prompt(shot, defaults, character)
        compiled.append({
            "id": shot["id"],
            "section": shot["section"],
            "bar": shot["bar"],
            "start": shot["start"],
            "end": shot["end"],
            "dur": shot["dur"],
            "model": shot["model"],
            "status": shot.get("status", "pending"),
            "caption": shot.get("caption", ""),
            "lyrics": [
                {"id": lid, "text": lyrics_by_id[lid]["text"]}
                for lid in shot.get("lyric_lines", []) if lid in lyrics_by_id
            ],
            "prompt": prompt,
            "negative": defaults["negative"],
            "aspect_ratio": defaults["aspect_ratio"],
            "character_ref": defaults["character_ref"],
            "hash": shot_hash(prompt, defaults["negative"], defaults["aspect_ratio"]),
        })
    return compiled


def to_markdown(project, compiled):
    """Group by model — the batches you actually paste, one interface at a time."""
    out = [
        f"# {project['project']} — shot prompts",
        "",
        f"{len(compiled)} shots · 16:9 · generated by `scripts/build_shots.py` — do not edit by hand.",
        "",
        "Generate **S12 first** and approve it, then use *its output* as the reference "
        "image for every other shot. Generating each shot from the original character "
        "sheet independently is what makes the character drift.",
        "",
    ]

    for model in sorted({c["model"] for c in compiled}):
        batch = [c for c in compiled if c["model"] == model]
        total = sum(c["dur"] for c in batch)
        out.append(f"## {model} — {len(batch)} shots, {total:.1f}s total")
        out.append("")
        for c in batch:
            out.append(f"### {c['id']} · {c['start']:.2f}–{c['end']:.2f}s "
                       f"({c['dur']:.2f}s) · bar {c['bar']} · {c['section']}")
            out.append("")
            out.append(f"- **hash** `{c['hash']}` · **status** {c['status']} "
                       f"· **ratio** {c['aspect_ratio']}")
            out.append(f"- **reference** `{c['character_ref']}`")
            if c["caption"]:
                out.append(f"- **caption card** 「{c['caption']}」 (overrides lyric subtitle)")
            if c["lyrics"]:
                for l in c["lyrics"]:
                    out.append(f"- **lyric** {l['id']} 「{l['text']}」")
            out.append("")
            out.append("```")
            out.append(c["prompt"])
            out.append("```")
            out.append("")
            out.append("Negative:")
            out.append("")
            out.append("```")
            out.append(c["negative"])
            out.append("```")
            out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--show", metavar="SHOT_ID", help="print one shot's prompt and exit")
    ap.add_argument("--model", help="print only the batch for one model and exit")
    args = ap.parse_args()

    project = load("project.json")
    book = load("storyboard/shots.json")

    lyrics_path = ROOT / "lyrics" / "lyrics.json"
    lyrics_by_id = {}
    if lyrics_path.exists():
        lyrics_by_id = {l["id"]: l for l in
                        json.loads(lyrics_path.read_text(encoding="utf-8"))["lines"]}
    else:
        print("note: lyrics/lyrics.json not found — run scripts/align_lyrics.py first",
              file=sys.stderr)

    compiled = compile_shots(project, book, lyrics_by_id)

    if args.show:
        match = next((c for c in compiled if c["id"] == args.show), None)
        if not match:
            sys.exit(f"no shot with id {args.show}")
        print(json.dumps(match, ensure_ascii=False, indent=2))
        return

    if args.model:
        batch = [c for c in compiled if c["model"] == args.model]
        if not batch:
            models = sorted({c["model"] for c in compiled})
            sys.exit(f"no shots for model {args.model!r}. Known: {', '.join(models)}")
        print(json.dumps(batch, ensure_ascii=False, indent=2))
        return

    out = ROOT / "out" / "shot_prompts.json"
    out.parent.mkdir(exist_ok=True)

    # Preserve prior hashes so we can report what actually changed.
    previous = {}
    if out.exists():
        previous = {s["id"]: s["hash"]
                    for s in json.loads(out.read_text(encoding="utf-8"))["shots"]}

    out.write_text(
        json.dumps({"project": project["project"], "shots": compiled},
                   ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (ROOT / "out" / "shot_prompts.md").write_text(
        to_markdown(project, compiled), encoding="utf-8")

    changed = [c["id"] for c in compiled if previous.get(c["id"]) != c["hash"]]
    print(f"compiled {len(compiled)} shots -> out/shot_prompts.json + shot_prompts.md")
    for model in sorted({c["model"] for c in compiled}):
        batch = [c for c in compiled if c["model"] == model]
        print(f"  {model:16s} {len(batch):2d} shots  {sum(c['dur'] for c in batch):6.1f}s")
    if previous:
        print(f"changed since last build: {', '.join(changed) if changed else '(none)'}")
    else:
        print("first build — all shots are new")


if __name__ == "__main__":
    main()
